### ISSUE TITLE
Hello Sir,Dev

### ISSUE THREAD

**Issue by MEGAUNLIMITEDSTORAGE** [Cyberavater/networkSample#1]
How can i contact you?

I will definately help you (no cost).
its my promise 
give us a chance.

**Comment by Cyberavater** [comment]
Bro, I'm literally working on better projects, I have no interest in working to fix that mega script (I don't even use Mega anymore). You are welcome to make a PR and I'll merge it.

**Comment by MEGAUNLIMITEDSTORAGE** [comment]
can you write looking for Unlimited Storage/Unlimited Transfer?

on your [Mega-Import-Bypass] Readme.md Script repo (at the top) here on your repo
i sell at extremely cheap.

as you help me i will also help you

I can provide u with a free new account(password u set)
which will come with
MEGA UNLIMITED STORAGE
MEGA UNLIMITED TRANSFER unlit validity. 

currently its 2 month.
